/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WNode {}
  interface WNodeEditor {}
}

declare global {


  interface HTMLWNodeElement extends Components.WNode, HTMLStencilElement {}
  var HTMLWNodeElement: {
    prototype: HTMLWNodeElement;
    new (): HTMLWNodeElement;
  };

  interface HTMLWNodeEditorElement extends Components.WNodeEditor, HTMLStencilElement {}
  var HTMLWNodeEditorElement: {
    prototype: HTMLWNodeEditorElement;
    new (): HTMLWNodeEditorElement;
  };
  interface HTMLElementTagNameMap {
    'w-node': HTMLWNodeElement;
    'w-node-editor': HTMLWNodeEditorElement;
  }
}

declare namespace LocalJSX {
  interface WNode {}
  interface WNodeEditor {}

  interface IntrinsicElements {
    'w-node': WNode;
    'w-node-editor': WNodeEditor;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'w-node': LocalJSX.WNode & JSXBase.HTMLAttributes<HTMLWNodeElement>;
      'w-node-editor': LocalJSX.WNodeEditor & JSXBase.HTMLAttributes<HTMLWNodeEditorElement>;
    }
  }
}


