name: CI
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn workspaces run lint:ci

      - name: Run unit tests and e2e tests
        run: yarn workspaces run test:ci
