name: GitHub Pages
on:
  workflow_run:
    workflows: ['CI']
    branches: [master]
    types:
      - completed
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Deploy
        run: |
          rsync -r --exclude=__tests__ src/ dist
          cd dist
          cp index.html 404.html
          git init
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git add -A
          git commit -m 'deploy'
          git push -f https://x-access-token:${{ github.token }}@github.com/${{ github.repository }} master:gh-pages
